M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu23.04.1} date Fri 28 Jul 2023 07:39:51 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-28T19:39:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.835Y-0.0177
X1.0626Y-0.0177
T0
M30
